apiVersion: v1
kind: Service
metadata:
  name: colourapp-blue
spec:
  selector:
    app: colourapp-blue
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
  type: NodePort
