apiVersion: apps/v1
kind: Deployment
metadata:
  name: colourapp-blue
  labels:
    app: colourapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: colourapp-blue
  template:
    metadata:
      labels:
        app: colourapp-blue
    spec:
      containers:
      - name: colourapp
        image: davevans/colourapp:latest
        ports:
        - containerPort: 80
        env:
        - name: COLOUR
          value: Blue          